/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranaypatodi
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMAR = new javax.swing.JLabel();
        LabelMBR = new javax.swing.JLabel();
        jTextFieldR1 = new javax.swing.JTextField();
        jTextFieldMBR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonR0 = new javax.swing.JButton();
        jButtonR1 = new javax.swing.JButton();
        jButtonR2 = new javax.swing.JButton();
        jButtonR3 = new javax.swing.JButton();
        jButtonX2 = new javax.swing.JButton();
        jButtonX3 = new javax.swing.JButton();
        jButtonX1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonInputRead = new javax.swing.JButton();
        jButtonInputWrite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInstructions = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldMAR = new javax.swing.JTextField();
        jTextFieldR0 = new javax.swing.JTextField();
        jTextFieldR3 = new javax.swing.JTextField();
        jTextFieldR2 = new javax.swing.JTextField();
        jTextFieldX3 = new javax.swing.JTextField();
        jTextFieldX2 = new javax.swing.JTextField();
        jTextFieldX1 = new javax.swing.JTextField();
        jButtonMBR = new javax.swing.JButton();
        jButtonMAR = new javax.swing.JButton();
        jLabelR3 = new javax.swing.JLabel();
        jTextFieldPC = new javax.swing.JTextField();
        jButtonPC = new javax.swing.JButton();
        LabelPC = new javax.swing.JLabel();
        LabelR0 = new javax.swing.JLabel();
        LabelR1 = new javax.swing.JLabel();
        jLabelR2 = new javax.swing.JLabel();
        jLabelX3 = new javax.swing.JLabel();
        jLabelX1 = new javax.swing.JLabel();
        jLabelX2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldInputAdress = new javax.swing.JTextField();
        jTextFieldInputValue = new javax.swing.JTextField();
        jLabelInputValue = new javax.swing.JLabel();
        jLabelInputAddress = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonSingleRun = new javax.swing.JButton();
        jButtonIPL = new javax.swing.JButton();
        jButtonLoad = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldMFR = new javax.swing.JTextField();
        jTextFieldCC = new javax.swing.JTextField();
        jTextFieldIR = new javax.swing.JTextField();
        jLabelMFR = new javax.swing.JLabel();
        jLabelIR = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jTextFieldMSR = new javax.swing.JTextField();
        jLabelMSR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelMAR.setText("MAR");
        getContentPane().add(LabelMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, 30));

        LabelMBR.setText("MBR");
        getContentPane().add(LabelMBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 30));

        jTextFieldR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 320, -1));
        getContentPane().add(jTextFieldMBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 320, -1));

        jLabel3.setText("Instructions");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jButtonR0.setText("Write");
        jButtonR0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonR0, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jButtonR1.setText("Write");
        jButtonR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jButtonR2.setText("Write");
        jButtonR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jButtonR3.setText("Write");
        jButtonR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jButtonX2.setText("Write");
        jButtonX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jButtonX3.setText("Write");
        jButtonX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jButtonX1.setText("Write");
        jButtonX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel4.setText("General Purpose Registers");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setText("Instruction Registers");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButtonInputRead.setText("Read");
        jButtonInputRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputReadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInputRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, -1, -1));

        jButtonInputWrite.setText("Write");
        jButtonInputWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputWriteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInputWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, -1, -1));

        jScrollPane1.setViewportView(jTextPaneInstructions);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 480, 590));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 440, 10));

        jTextFieldMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMARActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 320, -1));

        jTextFieldR0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR0ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldR0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 320, -1));

        jTextFieldR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 320, -1));

        jTextFieldR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 320, -1));

        jTextFieldX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldX3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 320, -1));

        jTextFieldX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldX2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 320, -1));

        jTextFieldX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldX1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 320, -1));

        jButtonMBR.setText("Write");
        jButtonMBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMBRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jButtonMAR.setText("Write");
        jButtonMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabelR3.setText("R3");
        getContentPane().add(jLabelR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 30));
        getContentPane().add(jTextFieldPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 320, -1));

        jButtonPC.setText("Write");
        jButtonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        LabelPC.setText("PC");
        getContentPane().add(LabelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        LabelR0.setText("R0");
        getContentPane().add(LabelR0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        LabelR1.setText("R1");
        getContentPane().add(LabelR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 30));

        jLabelR2.setText("R2");
        getContentPane().add(jLabelR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 30));

        jLabelX3.setText("X3");
        getContentPane().add(jLabelX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 220, 30));

        jLabelX1.setText("X1");
        getContentPane().add(jLabelX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 220, 30));

        jLabelX2.setText("X2");
        getContentPane().add(jLabelX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 220, 30));

        jLabel14.setText("Input");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 960, 10));

        jTextFieldInputAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputAdressActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldInputAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 670, 280, -1));

        jTextFieldInputValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputValueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldInputValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 380, -1));

        jLabelInputValue.setText("Value:");
        getContentPane().add(jLabelInputValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 60, 30));

        jLabelInputAddress.setText("Address:");
        getContentPane().add(jLabelInputAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 670, 60, 30));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 970, 10));

        jButtonSingleRun.setText("Single Run");
        getContentPane().add(jButtonSingleRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, -1, -1));

        jButtonIPL.setText("IPL");
        getContentPane().add(jButtonIPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, -1, -1));

        jButtonLoad.setText("Load");
        getContentPane().add(jButtonLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, -1, -1));

        jButtonStop.setText("Stop");
        getContentPane().add(jButtonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 710, -1, -1));

        jButtonStart.setText("Start");
        getContentPane().add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 440, 10));

        jLabel15.setText("16 bit");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 440, 10));

        jTextFieldMFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMFRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 390, -1));

        jTextFieldCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 390, -1));

        jTextFieldIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 390, -1));

        jLabelMFR.setText("MFR");
        getContentPane().add(jLabelMFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 290, 30));

        jLabelIR.setText("IR");
        getContentPane().add(jLabelIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, 30));

        jLabelCC.setText("CC");
        getContentPane().add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 290, 30));

        jTextFieldMSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMSRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 390, -1));

        jLabelMSR.setText("MSR");
        getContentPane().add(jLabelMSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 290, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR1ActionPerformed

    private void jButtonR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR1ActionPerformed
        Simulator.gpr[1] = jTextFieldR1.getText();
    }//GEN-LAST:event_jButtonR1ActionPerformed

    private void jButtonInputReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputReadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInputReadActionPerformed

    private void jTextFieldMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMARActionPerformed
    }//GEN-LAST:event_jTextFieldMARActionPerformed

    private void jTextFieldR0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR0ActionPerformed

    private void jTextFieldR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR3ActionPerformed

    private void jTextFieldR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR2ActionPerformed

    private void jTextFieldX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX3ActionPerformed

    private void jTextFieldX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX2ActionPerformed

    private void jTextFieldX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX1ActionPerformed

    private void jButtonR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR2ActionPerformed
        Simulator.gpr[2] = jTextFieldR1.getText();
    }//GEN-LAST:event_jButtonR2ActionPerformed

    private void jButtonIPLPerformed(java.awt.event.ActionEvent evt) {
        Simulator.setIPL(Simulator.IPL);
        /*
        for (int i = 0; i<Simulator.IPL.length; i++) {
            Simulator.pushInstList(Simulator.IPL[i]);
        }
         */
    }

    private void jButtonSingleRunPerformed(java.awt.event.ActionEvent evt) {
        if (Simulator.execPos < 5) {
            Simulator.execInst(Simulator.IPL[Simulator.execPos]);
            showCurrentContent();
            Simulator.execPos++;
        }
    }

    private void jTextFieldInputAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInputAdressActionPerformed

    private void jTextFieldInputValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInputValueActionPerformed

    private void jTextFieldMFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMFRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMFRActionPerformed

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jTextFieldIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIRActionPerformed

    private void jTextFieldMSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMSRActionPerformed

    private void jButtonMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMARActionPerformed
        Simulator.mar = jTextFieldMAR.getText();
    }//GEN-LAST:event_jButtonMARActionPerformed

    private void jButtonMBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMBRActionPerformed
        Simulator.mbr = jTextFieldMBR.getText();
    }//GEN-LAST:event_jButtonMBRActionPerformed

    private void jButtonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPCActionPerformed
        Simulator.pc = jTextFieldPC.getText();
    }//GEN-LAST:event_jButtonPCActionPerformed

    private void jButtonR0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR0ActionPerformed
        Simulator.gpr[0] = jTextFieldR0.getText();
    }//GEN-LAST:event_jButtonR0ActionPerformed

    private void jButtonR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR3ActionPerformed
        Simulator.gpr[3] = jTextFieldR3.getText();
    }//GEN-LAST:event_jButtonR3ActionPerformed

    private void jButtonX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX1ActionPerformed
        Simulator.indexRegister[0] = jTextFieldX1.getText();
    }//GEN-LAST:event_jButtonX1ActionPerformed

    private void jButtonX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX2ActionPerformed
        Simulator.indexRegister[1] = jTextFieldX2.getText();
    }//GEN-LAST:event_jButtonX2ActionPerformed

    private void jButtonX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX3ActionPerformed
        Simulator.indexRegister[2] = jTextFieldX3.getText();
    }//GEN-LAST:event_jButtonX3ActionPerformed

    private void jButtonInputWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputWriteActionPerformed
        String ins;
        int counter = 0;
        ins = jLabelInputValue.getText();
        Simulator.instList[counter] = ins;
        Simulator.execInst(ins);
        showCurrentContent();
        for(int i = 0; i <= counter; i++){
            jTextPaneInstructions.setText(Simulator.instList[i]);
        }
    }//GEN-LAST:event_jButtonInputWriteActionPerformed

    private void showCurrentContent(){
        jTextFieldMAR.setText(Simulator.mar);
        jTextFieldMBR.setText(Simulator.mbr);
        jTextFieldPC.setText(Simulator.pc);
        jTextFieldMAR.setText(Simulator.mar);
        jTextFieldR0.setText(Simulator.gpr[0]);
        jTextFieldR1.setText(Simulator.gpr[1]);
        jTextFieldR2.setText(Simulator.gpr[2]);
        jTextFieldR3.setText(Simulator.gpr[3]);
        jTextFieldX1.setText(Simulator.indexRegister[0]);
        jTextFieldX2.setText(Simulator.indexRegister[1]);
        jTextFieldX3.setText(Simulator.indexRegister[2]);
        //jTextFieldIR.setText(Simulator.instList[]);
        //jTextFieldCC.setText(Simulator.cc);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Simulator.initMem();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMAR;
    private javax.swing.JLabel LabelMBR;
    private javax.swing.JLabel LabelPC;
    private javax.swing.JLabel LabelR0;
    private javax.swing.JLabel LabelR1;
    private javax.swing.JButton jButtonIPL;
    private javax.swing.JButton jButtonInputRead;
    private javax.swing.JButton jButtonInputWrite;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonMAR;
    private javax.swing.JButton jButtonMBR;
    private javax.swing.JButton jButtonPC;
    private javax.swing.JButton jButtonR0;
    private javax.swing.JButton jButtonR1;
    private javax.swing.JButton jButtonR2;
    private javax.swing.JButton jButtonR3;
    private javax.swing.JButton jButtonSingleRun;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonX1;
    private javax.swing.JButton jButtonX2;
    private javax.swing.JButton jButtonX3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelIR;
    private javax.swing.JLabel jLabelInputAddress;
    private javax.swing.JLabel jLabelInputValue;
    private javax.swing.JLabel jLabelMFR;
    private javax.swing.JLabel jLabelMSR;
    private javax.swing.JLabel jLabelR2;
    private javax.swing.JLabel jLabelR3;
    private javax.swing.JLabel jLabelX1;
    private javax.swing.JLabel jLabelX2;
    private javax.swing.JLabel jLabelX3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldIR;
    private javax.swing.JTextField jTextFieldInputAdress;
    private javax.swing.JTextField jTextFieldInputValue;
    private javax.swing.JTextField jTextFieldMAR;
    private javax.swing.JTextField jTextFieldMBR;
    private javax.swing.JTextField jTextFieldMFR;
    private javax.swing.JTextField jTextFieldMSR;
    private javax.swing.JTextField jTextFieldPC;
    private javax.swing.JTextField jTextFieldR0;
    private javax.swing.JTextField jTextFieldR1;
    private javax.swing.JTextField jTextFieldR2;
    private javax.swing.JTextField jTextFieldR3;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldX2;
    private javax.swing.JTextField jTextFieldX3;
    private javax.swing.JTextPane jTextPaneInstructions;
    // End of variables declaration//GEN-END:variables
}
